# Generated by Django 4.0.4 on 2022-05-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='promocion',
            field=models.IntegerField(),
        ),
    ]
