# Generated by Django 4.0.4 on 2022-05-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_persona_cargo_persona_titulo_habilitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('cargo', models.CharField(default='', max_length=30)),
                ('titulo_habilitante', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='titulo_habilitante',
        ),
    ]
