# Generated by Django 4.0.4 on 2022-06-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_libros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='año',
            new_name='ano',
        ),
    ]
