# Generated by Django 4.0.4 on 2022-06-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_rename_año_libros_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('copia', models.IntegerField()),
                ('editorial', models.CharField(max_length=200)),
                ('nivel', models.CharField(max_length=200)),
                ('retiro', models.CharField(max_length=200)),
                ('fecha_retiro', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Libros',
        ),
    ]
