# Generated by Django 4.0.4 on 2022-06-21 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_libro_delete_libros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_retiro',
        ),
    ]
